# OnePlus 9 Pro target profile
name=OnePlus 9 Pro
product_device=OnePlus9Pro
codename=lemonadep
model_prefix=LE212
soc=SM8350
# Reference: tqmane/coloros_port bin/getSuperSize.sh
super_size=11190403072
